PatientSystem_v1.01/PatientSystem_v1.01/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PatientSystem_v1._01.Models
{
    public class Patient
    {
        public int PatientId { get; set; }
        [Display(Name = "First Name")]
        public string FName { get; set; }
        [Display(Name = "Last Name")]
        public string LName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date Of Birth")]
        public string DOB { get; set; }
        [Display(Name = "Active")]
        public bool isActive { get; set; }
        public string Disease { get; set; }
    }
}

PatientSystem_v1.01/PatientSystem_v1.01/Models/PatientBussiness.cs
using Sevices;
using Web;
using DataLayer;
using PatientSystem_v1._01.Context;
using System.Collections.Generic;
using System.Linq;



namespace PatientSystem_v1._01.Models
{
    public class PatientBussiness
    {
        private Data data = new Data();
        private Sevice service = new Sevice();
        private PatientContext db = new PatientContext();
        public List<Patient> View(string search)
        {
            string Search = service.CheckSearch(search);

            return db.Patients.Where(s=>s.FName.StartsWith(Search) ||
            s.LName.StartsWith(Search) ||
            s.Disease.StartsWith(Search) ||
            s.DOB.StartsWith(Search) ||
            Search == string.Empty).ToList();
        }
        public Patient Find(int? Id)
        {
            if (Id!=0)
            {
                return db.Patients.Find(Id);
            }
            else
            {
                return new Patient();
            }
        }
        public void Delete(Patient patient)
        {
            db.Patients.Remove(patient);
            db.SaveChanges();
        }
        public void AddOrEdit(Patient patient)
        {
            if(patient.PatientId == 0)
            {
                db.Patients.Add(patient);
                db.SaveChanges();
            }
            else
            {
                var Patient = db.Patients.Where(p => p.PatientId == patient.PatientId).FirstOrDefault();
                db.Patients.Remove(Patient);
                db.Patients.Add(patient);
                db.SaveChanges();
            }
        }
    }
}

PatientSystem_v1.01/PatientSystem_v1.01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PatientSystem_v1._01.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PatientSystem_v1.01/PatientSystem_v1.01/Controllers/PatientsController.cs
using PatientSystem_v1._01.Models;
using System.Web.Mvc;
using PagedList;

namespace PatientSystem_v1._01.Controllers
{
    public class PatientsController : Controller
    {
        PatientBussiness patientBuseniss = new PatientBussiness();
        public ActionResult Index(int? i, string search)
       {
            return View(patientBuseniss.View(search).ToPagedList(i ?? 1,3));
        }
        public ActionResult Details(int Id)
        {
            return View(patientBuseniss.Find(Id));
        }
        public ActionResult Edit(int Id)
        {
            return View(patientBuseniss.Find(Id));
        }
        [HttpPost]
        public ActionResult Edit(Patient patient)
        {
            patientBuseniss.AddOrEdit(patient);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int? Id)
        {
            return View(patientBuseniss.Find(Id));
        }
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            Patient patient = patientBuseniss.Find(Id);
            patientBuseniss.Delete(patient);
            return RedirectToAction("Index");
        }
    }
}

PatientSystem_v1.01/PatientSystem_v1.01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PatientSystem_v1.01/PatientSystem_v1.01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PatientSystem_v1.01/PatientSystem_v1.01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PatientSystem_v1.01/PatientSystem_v1.01/Views/Patients/Delete.cshtml
@model PatientSystem_v1._01.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disease)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disease)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PatientSystem_v1.01/PatientSystem_v1.01/Views/Patients/Details.cshtml
@model PatientSystem_v1._01.Models.Patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disease)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disease)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PatientSystem_v1.01/PatientSystem_v1.01/Views/Patients/Edit.cshtml
@model PatientSystem_v1._01.Models.Patient


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PatientId)

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disease, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Disease, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Disease, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PatientSystem_v1.01/PatientSystem_v1.01/Views/Patients/Index.cshtml
@model IPagedList<PatientSystem_v1._01.Models.Patient>

@{
    ViewBag.Title = "Index";
}

@using PagedList;
@using PagedList.Mvc;

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Edit", new {id = 0 })
    @using (Html.BeginForm("index","Patients",FormMethod.Get))
    {
        <input type="text" name="search" placeholder="Search Name..." class="form-control" />
        <input type="submit" name="submit" value="Search" class="btn btn-primary" />
    }
</p>
<br />  
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().isActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Disease)
        </th>
        <th></th>
    </tr>
    <tbody id="PatientsTable">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Disease)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.PatientId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.PatientId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.PatientId })
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model, i => Url.Action("Index", "Patients", 
    new { i, search = Request.QueryString["search"] }))

PatientSystem_v1.01/PatientSystem_v1.01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>